# Generated by Django 5.1.3 on 2026-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BpaApac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpaapacimporthistory',
            name='apac_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bpaapacimporthistory',
            name='bpa_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
